### PR TITLE
add call to GitHub to create an issue

### PR DESCRIPTION
**Pull request by jlfabi**
- add call to GitHub to create issues
- created test. dev dependencies and test folder added. any side effects there?

#2

### CODE REVIEW

**Comment by jlfabi** [comment]
I set my spaces to 4. That seemed to create some formatting updates. Let me know if that is a problem
Screen Shot 2022-09-29 at 9 30 25 AM

**Comment by liveacid** [comment]
> * I set my spaces to 4. That seemed to create some formatting updates. Let me know if that is a problem
> 
> Screen Shot 2022-09-29 at 9 30 25 AM
> 
> * axios version was updated to a specific version. Is that a problem?

Yes. I fixed the axios issue tho

**Review by liveacid — COMMENTED** [review]
Added some minor changes but it works. ready to merge

**Review by liveacid — APPROVED** [review]
approved

**Pull request merged**
